from pptx import Presentation
from pptx.util import Inches, Pt
import os
from config import Config

def generate_pptx(data: dict, output_filename: str) -> str:
    """
    Generates a PowerPoint file from the structured JSON data.
    """
    prs = Presentation()
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = data.get("title", "Generated Presentation")
    subtitle.text = "Generated by AI Voice-to-Presentation"
    
    # Content Slides
    bullet_slide_layout = prs.slide_layouts[1]
    
    for slide_data in data.get("slides", []):
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        
        title_shape = shapes.title
        body_shape = shapes.placeholders[1]
        
        title_shape.text = slide_data.get("title", "Untitled Slide")
        
        tf = body_shape.text_frame
        
        bullet_points = slide_data.get("bullet_points", [])
        if bullet_points:
            tf.text = bullet_points[0]
            for point in bullet_points[1:]:
                p = tf.add_paragraph()
                p.text = point
                p.level = 0
        
        # Add speaker notes
        notes_slide = slide.notes_slide
        text_frame = notes_slide.notes_text_frame
        text_frame.text = slide_data.get("speaker_notes", "")
        
    output_path = os.path.join(Config.OUTPUT_DIR, output_filename)
    prs.save(output_path)
    
    return output_path
