from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
import os
import requests
from io import BytesIO
from config import Config

def hex_to_rgb(hex_color):
    """Convert hex string (e.g., #FFFFFF) to RGB tuple."""
    try:
        hex_color = hex_color.lstrip('#')
        return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))
    except:
        return (0, 0, 0) # Fallback to black

def download_image(query):
    """Download an AI generated image from Pollinations.ai based on query."""
    try:
        # Encode query to URL safe
        encoded_query = requests.utils.quote(query)
        # Request a specific size suitable for slides
        url = f"https://image.pollinations.ai/prompt/{encoded_query}?width=800&height=600&nologo=true&seed=42"
        # Seed added for consistency, nologo to remove watermark if possible
        response = requests.get(url, timeout=15) # Increased timeout for AI generation
        if response.status_code == 200:
            return BytesIO(response.content)
    except Exception as e:
        print(f"Error downloading image for '{query}': {e}")
    return None

def generate_pptx(data: dict, output_filename: str) -> str:
    """
    Generates a PowerPoint file from the structured JSON data with Styles and Images.
    """
    prs = Presentation()
    
    # Extract Visual Style
    style = data.get("visual_style", {})
    bg_color_hex = style.get("background_color", "#FFFFFF")
    text_color_hex = style.get("text_color", "#000000")
    accent_color_hex = style.get("accent_color", "#0000FF")
    
    bg_rgb = hex_to_rgb(bg_color_hex)
    text_rgb = hex_to_rgb(text_color_hex)
    accent_rgb = hex_to_rgb(accent_color_hex)

    # --- Title Slide ---
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    
    # Apply Background
    background = slide.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(*bg_rgb)
    
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = data.get("title", "Generated Presentation")
    # Apply accent color to title
    if title.text_frame:
        for p in title.text_frame.paragraphs:
            p.font.color.rgb = RGBColor(*accent_rgb)
    
    subtitle.text = "Generated by AI Voice-to-Presentation"
    # Apply text color to subtitle
    if subtitle.text_frame:
        for p in subtitle.text_frame.paragraphs:
            p.font.color.rgb = RGBColor(*text_rgb)
    
    # --- Content Slides ---
    # Using Blank layout (6) to custom position everything for better design control
    blank_slide_layout = prs.slide_layouts[6] 
    
    for slide_data in data.get("slides", []):
        slide = prs.slides.add_slide(blank_slide_layout)
        
        # Apply Background
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = RGBColor(*bg_rgb)
        
        # 1. Title (Top, Full Width)
        # Left, Top, Width, Height
        title_shape = slide.shapes.add_textbox(Inches(0.5), Inches(0.4), Inches(9), Inches(1))
        title_tf = title_shape.text_frame
        title_tf.text = slide_data.get("title", "Untitled Slide")
        title_p = title_tf.paragraphs[0]
        title_p.font.size = Pt(36)
        title_p.font.bold = True
        title_p.font.color.rgb = RGBColor(*accent_rgb)
        
        # 2. Image (Right Side) - Try to fetch if query exists
        image_stream = None
        if "image_query" in slide_data:
            print(f"Downloading image: {slide_data['image_query']}")
            image_stream = download_image(slide_data["image_query"])
            
        if image_stream:
            # Layout: Text Left, Image Right
            # Image: Left=5.5, Top=1.8, Width=4
            try:
                slide.shapes.add_picture(image_stream, Inches(5.5), Inches(1.8), width=Inches(4))
            except Exception as img_err:
                print(f"Failed to add picture to slide: {img_err}")
            
            # Content Text Box (Left Side, narrower)
            body_shape = slide.shapes.add_textbox(Inches(0.5), Inches(1.8), Inches(4.8), Inches(5))
        else:
            # Layout: Full Width Text
            body_shape = slide.shapes.add_textbox(Inches(0.5), Inches(1.8), Inches(9), Inches(5))
            
        tf = body_shape.text_frame
        tf.word_wrap = True
        
        bullet_points = slide_data.get("bullet_points", [])
        if bullet_points:
            # First point (needed because text_frame starts with one empty paragraph)
            p = tf.paragraphs[0]
            p.text = bullet_points[0]
            p.font.size = Pt(20)
            p.font.color.rgb = RGBColor(*text_rgb)
            p.space_after = Pt(14)
            # Use a dash as bullet visually since we are using textbox
            if not p.text.startswith("-") and not p.text.startswith("•"):
                p.text = "• " + p.text
            
            # Other points
            for point in bullet_points[1:]:
                p = tf.add_paragraph()
                p.text = "• " + point
                p.font.size = Pt(20)
                p.font.color.rgb = RGBColor(*text_rgb)
                p.space_after = Pt(14)
        
        # Add speaker notes
        notes_slide = slide.notes_slide
        text_frame = notes_slide.notes_text_frame
        text_frame.text = slide_data.get("speaker_notes", "")
        
    output_path = os.path.join(Config.OUTPUT_DIR, output_filename)
    prs.save(output_path)
    
    return output_path
